
version: '3.8'
services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"             # 웹 UI 접근용 (외부 → 내부 80)
      - "16001:16001"         # internal 통신 포트 (예: agent와 통신)
      - "12000-12009:12000-12009"  # agent와의 연결 포트 범위
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
    networks:
      - capston-design-network

  agent:
    image: ngrinder/agent
    restart: always
    networks:
      - capston-design-network

networks:
  capston-design-network:
    external: true