version: '3'

services:
  frontend:
    image: k2c1/capston-design-frontend
    ports:
      - "80:80"
    networks:
      - capston-design-network


  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - "-nginx.scrape-uri=http://frontend:80/nginx_status"
    ports:
      - "9113:9113"
    networks:
      - capston-design-network


networks:
  capston-design-network:
    external: true
