version: '3'
services:
  backend:
    image: k2c1/capston-design-backend
    ports:
      - "8080:8080"
      - "9999:9999"
    networks:
      - capston-design-network

networks:
  capston-design-network:
    external: true



